import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  Future<void> generateAndPrint(
    Map<String, dynamic> record,
    Map<String, dynamic> patientProfile, {
    String? doctorName,
  }) async {
    final pdf = pw.Document();

    final date = DateTime.parse(record['start_time']).toLocal();
    final bpmData = List<int>.from(record['bpm_data'] ?? []);
    final title = 'Fetal Heart Rate Monitoring Report';

    // Calculate Chart Points
    final chartPoints = <pw.PointChartValue>[];
    for (int i = 0; i < bpmData.length; i++) {
      chartPoints.add(pw.PointChartValue(i.toDouble(), bpmData[i].toDouble()));
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // HEADER
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        title,
                        style: pw.TextStyle(
                          fontSize: 24,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.pink800,
                        ),
                      ),
                      pw.Text(
                        'Generated by Dopply',
                        style: const pw.TextStyle(
                          fontSize: 10,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        'Date: ${DateFormat('dd MMM yyyy').format(date)}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                      pw.Text(
                        'Time: ${DateFormat('HH:mm').format(date)}',
                        style: const pw.TextStyle(fontSize: 12),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // PATIENT & CLINICAL INFO
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: pw.Container(
                    padding: const pw.EdgeInsets.all(10),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey300),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          'Patient Details',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        ),
                        pw.Divider(thickness: 0.5),
                        _buildInfoRow(
                          'Name',
                          patientProfile['full_name'] ?? 'Unknown',
                        ),
                        _buildInfoRow(
                          'HPHT',
                          patientProfile['patient_data']?['hpht'] ?? '-',
                        ),
                        _buildInfoRow(
                          'Gestational Age',
                          '${record['gestational_age_weeks'] ?? '-'} Weeks',
                        ),
                      ],
                    ),
                  ),
                ),
                pw.SizedBox(width: 20),
                pw.Expanded(
                  child: pw.Container(
                    padding: const pw.EdgeInsets.all(10),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey300),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          'Monitoring Summary',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        ),
                        pw.Divider(thickness: 0.5),
                        _buildInfoRow(
                          'Average BPM',
                          '${(record['average_bpm'] as num).toStringAsFixed(1)} BPM',
                        ),
                        _buildInfoRow(
                          'Duration',
                          '${(record['duration_minutes'] as num).toStringAsFixed(1)} Min',
                        ),
                        _buildInfoRow(
                          'Classification',
                          record['classification'] ?? 'Unknown',
                        ),
                        if (doctorName != null)
                          _buildInfoRow('Assigned Doctor', doctorName),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 20),

            // CHART
            pw.Text(
              'Heart Rate History (BPM)',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            pw.Container(
              height: 200,
              child: pw.Chart(
                grid: pw.CartesianGrid(
                  xAxis: pw.FixedAxis(
                    List.generate(
                      (bpmData.length / 60).ceil() + 1,
                      (index) => index * 60,
                    ),
                  ),
                  yAxis: pw.FixedAxis([60, 80, 100, 120, 140, 160, 180, 200]),
                ),
                datasets: [
                  pw.LineDataSet(
                    data: chartPoints,
                    color: PdfColors.pink500,
                    isCurved: true,
                    lineWidth: 2,
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 10),
            pw.Text(
              '* Y-Axis: BPM, X-Axis: Time (Minutes)',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
            pw.SizedBox(height: 20),

            // NOTES
            if (record['doctor_notes'] != null) ...[
              pw.Text(
                'Doctor Notes',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(8),
                margin: const pw.EdgeInsets.only(top: 5),
                color: PdfColors.grey100,
                child: pw.Text(record['doctor_notes']),
              ),
              pw.SizedBox(height: 10),
            ],
            if (record['notes'] != null) ...[
              pw.Text(
                'Patient Notes',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(8),
                margin: const pw.EdgeInsets.only(top: 5),
                color: PdfColors.grey50,
                child: pw.Text(record['notes']),
              ),
              pw.SizedBox(height: 20),
            ],

            pw.Spacer(),

            // FOOTER & DISCLAIMER
            pw.Divider(),
            pw.Text(
              'DISCLAIMER: This report is generated by an automated system and is intended for informational purposes only. '
              'It does NOT constitute a medical diagnosis. The classification provided is based on algorithm analysis and may not account for all clinical factors. '
              'Please consult a qualified healthcare provider for proper interpretation and medical advice.',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
              textAlign: pw.TextAlign.justify,
            ),
            pw.SizedBox(height: 5),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                pw.Text(
                  'Dopply - Advanced Fetal Monitoring System',
                  style: const pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey500,
                  ),
                ),
              ],
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Dopply_Report_${DateFormat('yyyyMMdd_HHmm').format(date)}',
    );
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
          ),
        ],
      ),
    );
  }
}
